sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t mmiskinis/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true mmiskinis/react-test npm test -- --coverage

after_success:
  - docker build -t mmiskinis/multi-client ./client
  - docker build -t mmiskinis/multi-nginx ./nginx
  - docker build -t mmiskinis/multi-server ./server
  - docker build -t mmiskinis/multi-worker ./worker
  # push to docker hub
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push mmiskinis/multi-client
  - docker push mmiskinis/multi-nginx
  - docker push mmiskinis/multi-server
  - docker push mmiskinis/multi-worker